[[courses]]
name = "Cornell CS 4750/5750: Foundations of Robotics"
year = 2016
url = "https://rpal.cs.cornell.edu/foundations/"
authors = "Knepper, Ross A. and Mavrogiannis, Christoforos and Proft, Julia and Thomason, Wil"
