# Site settings
title: Wil Thomason
email: first.last@google's email service
description: A personal blog focusing on mathematics, computer science, and related topics.
baseurl: "/blog"
url: "http://wbthomason.co" 
twitter_username: wilthomason
github_username:  wbthomason
titlecase: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exerpt_separator: <!--more-->

gems:
  - jekyll-smartify
  - jekyll-timeago
