# Site settings
title: wil thomason
email: wbthomason@{my department, abbr.}.{my university}.edu
description: "The professional site of Wil Thomason"
baseurl: ""
url: "http://wbthomason.co" 
twitter_username: wilthomason
github_username:  wbthomason
titlecase: false

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exerpt_separator: <!--more-->

gems:
  - jekyll-smartify
  - jekyll-timeago
