baseurl = "https://www.cs.cornell.edu/~wil/"
languageCode = "en-us"
title = "wil thomason"
theme = "lanyon"
googleAnalytics = "UA-75724004-1"
canonifyURLs = true

[params]
  author = "Wil Thomason"
  title = "wil thomason"
  Github = "wbthomason"
  Twitter = "wilthomason"
  Linkedin = "wbthomason"
  Email = "wbthomason@{my department, abbr.}.{my university}.edu"
  DateForm = "%M.%D.%Y %hh:%mm:%ss"
