base_url = "https://wbthomason.com"
compile_sass = true
build_search_index = false
ignored_content = ["**/*.bib", "**/*.toml"]

[markdown]
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
smart_punctuation = true

[extra]
# Put all your custom variables here
