[[grants]]
coauthor = true
title = "Synergy: Coordinated Action Among Independent Mobile Cyber-Physical Systems"
url = "https://www.nsf.gov/awardsearch/showAward?AWD_ID=1646417&amp;HistoricalAwards=false"
authors = "Knepper, Ross A. and Morrisett, Greg and Anand, Abhishek and Thomason, Wil"
