# On every push this script is executed
on:
 workflow_dispatch:
 push:
  branches:
   - zola
name: Build and deploy GH Pages
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          ref: zola
      - name: build_and_deploy
        uses: shalzz/zola-deploy-action@v0.17.2
        env:
          # Target branch
          PAGES_BRANCH: master
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
